[package]
name = "path_function"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
common = { path = "../common" }

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]